version: '3.9'

services:

  postgres:
    image: postgres:16.2-alpine
    restart: unless-stopped
    ports:
      - "5462:5432"
    env_file:
      - .env
    volumes:
      - .docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}' ]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis:7.0.11
    restart: unless-stopped
    ports:
      - "6379:6379"
    env_file:
      - .env
    volumes:
      - .docker/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 20s
      retries: 3

  minio:
    image: minio/minio:RELEASE.2023-07-07T07-13-57Z
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - .docker/minio:/data
    command: server --console-address ":9001" /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3